# Setup
name:         Project or Site name (Architect Theme)
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
